### ISSUE TITLE
error sharp module

### ISSUE THREAD

**Issue by dnamyslak** [oslllo/svg-fixer#7]
I am getting:

Error: 
Something went wrong installing the "sharp" module

**Comment by dnamyslak** [comment]
unless you update 
here is the solution

https://blog.joshwalsh.me/gatsby-update-sharp/

**Comment by Ghustavh97** [comment]
@dnamyslak Thanks for the solution but I will need the `full` error message to help verify the problem and push and update if need be.

**Comment by dnamyslak** [comment]
full error:

`"C:\Program Files\nodejs\node.exe" X:\DAVEN\nodejs-temp\bin\www
X:\DAVEN\nodejs-temp\node_modules\sharp\lib\constructor.js:34
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

Nie mo¿na odnaleæ okrelonej procedury.
\\?\X:\DAVEN\nodejs-temp\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (X:\DAVEN\nodejs-temp\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (X:\DAVEN\nodejs-temp\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

Process finished with exit code 1`

**Comment by dnamyslak** [comment]
the solution for you is mentioned here: https://blog.joshwalsh.me/gatsby-update-sharp/ 
you need to "update dependency to the latest version"
