### ISSUE TITLE
destination only accept folder path, no filename

### ISSUE THREAD

**Issue by iyh** [oslllo/svg-fixer#70]
If user want change the output filename, for eg. `oslllo-svg-fixer -s \!.svg -d fixed/exclamationmark.svg`
will produce error:
```
ERR: destination path fixed/exclamationmark.svg does not exist.

STACK: TypeError: destination path fixed/exclamationmark.svg does not exist.
    at Object.invalidPathError (~/.nvm/versions/node/v16.13.2/lib/node_modules/oslllo-svg-fixer/src/error.js:27:10)
    at new Location (~/.nvm/versions/node/v16.13.2/lib/node_modules/oslllo-svg-fixer/src/location.js:21:19)
...
```
so maybe check if destination  has ext? `path.parse(destination).ext` before check exists  [/src/location.js#L19](https://github.com/oslllo/svg-fixer/blob/master/src/location.js#L19)

**Comment by iyh** [comment]
I get your point, your using case is more effective , convert all svgs even those ones is OK in icomoon. 
(for eg. only some of svgs in one icon pack are Strokes)
